config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'page1', to: 'pages#page1'
  get 'page2', to: 'pages#page2'
  get 'page3', to: 'pages#page3'
  get 'page4', to: 'pages#page4'
  get 'page5', to: 'pages#page5'
  get 'rankingpage', to: 'pages#rankingpage'

  # declares all index, show , new, edit and destroy actions
  resources :pages do
    resources :ranks
  end
  root 'pages#index'
  root to: 'home#index'

  # invalid path redirect
get '*path', to: 'phones#not_found'

end

app/models/rank.rb
class Rank < ApplicationRecord

  # Every rank belongs to a page and a user
  belongs_to :page
  belongs_to :user
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController

# before_action is used to run some specific methods before the execution of certain methods
  before_action :find_page
  before_action :find_rank, only: [:destroy]

  # renders the new view in the rank views
  # set the rank variable equal to a newly created empty rank under the current user
  def new
    @rank = Rank.new
  end

  # set the rank variable equal to a newly created rank under the current user with all the params ented in the form
  # if the user is signed in then create the rank under the current user
  # if the rank is created and saved then go to rankingpage view else render ask user to login first
  def create
    @rank = Rank.new(rank_params)
    @rank.page_id = @page.id

    @rank.user_id = current_user.id if user_signed_in?

    if @rank.save
      redirect_to rankingpage_path
    else
      redirect_to new_user_session_path
    end
  end

# If a rank of a page is deleted then go to the ranking page
  def destroy
    @rank.destroy
    redirect_to rankingpage_path
  end

# private methods
  private

# All the parameters required for a rank that are required, added and permitted
  def rank_params
    params.require(:rank).permit(:rating)
  end

# Find a page by its unique id page_id from the db records and store it under the variable page
  def find_page
    @page = Page.find(params[:page_id])
  end

# Find a rank by its unique id from the db records and store it under the variable rank
  def find_rank
    @rank = Rank.find(params[:id])
  end
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/views/ranks/_form.html.erb
<%= simple_form_for([@page, @page.ranks.build]) do |f| %>
<label>
  <%= @page.title %>
  Rank
</label>
<div id="rank-form"></div>
<br>
<%= f.button :submit %>
<% end %>

<script>
$('#rank-form').raty({path: '/assets/', scoreName: 'rank[rating]'});
</script>

app/views/ranks/_rank.html.erb
<h5>
  <div class="rank-rating" data-score="<%= rank.rating %>"></div>

  <% if user_signed_in? %>
    <% if rank.user_id == current_user.id %>
      <p></p>
      <%= link_to "Delete", page_rank_path(rank.page, rank), method: :delete, data: { confirm: "Are you sure?" } %>

    <% end %>
  <% end %>

</h5>

app/views/ranks/new.html.erb
<div class="tile">

  <h1>
    Provide the article rank below
  </h1>

  <%= render 'form' %>

</div>