config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'page1', to: 'pages#page1'
  get 'page2', to: 'pages#page2'
  get 'page3', to: 'pages#page3'
  get 'page4', to: 'pages#page4'
  get 'page5', to: 'pages#page5'
  get 'rankingpage', to: 'pages#rankingpage'

  # declares all index, show , new, edit and destroy actions
  resources :pages do
    resources :ranks
  end
  root 'pages#index'
  root to: 'home#index'

  # invalid path redirect
get '*path', to: 'phones#not_found'

end

app/views/pages/_form.html.erb
<%= simple_form_for @page do |f| %>
<%= f.input :pageid, label: "Article No" %>
<%= f.input :title, label: "Title" %>
<label>
  Image
</label><%= f.file_field :page_image, label: "Image" %>
<br>
<%= f.button :submit %>
<% end %>

app/views/pages/_show.html.erb
<div class="tile">
<div class="row">


  <div class="col-md-4 col-md-offset-0">
  <h1><%= @page.title %></h1>
  <h4>Rank:
        <% if !@page.ranks.blank? %>
    <%= @page.ranks.average(:rating).round(0) %></h4>
<% end %>
<br>
<br>
  <% if user_signed_in? %>
    <% if @page.user_id == current_user.id %>

      <ul>
        <li><%= link_to "Edit", edit_page_path(@page) %></li>
      </ul>
      <ul>
        <li><%= link_to "Delete", page_path(@page), method: :delete, data: {confirm: "Are you sure ?" } %></li>
      </ul>
      <h1></h1>

    <% end %>
  <% end %>

  <br>
  <h4>
    Ranks previously given:
  </h4>
    <% if !@page.ranks.blank? %>
  <%= render @page.ranks %>
  <% end %>
  <br>
  <h4>
    Average rank:
  </h4>
  <div class="average-rank-rating" data-score=<%= @average_rank %>></div>
  <br>
  <br>
  <a href="/pages/<%= @page.id %>">
 <%= image_tag @page.page_image.url(:page_index) %>
 </a>
  </div>

  </div>
</div>


<script>
  $('.rank-rating').raty({
    readOnly: true,
    score: function () {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-rank-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function () {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/pages/edit.html.erb
<div class="tile">

  <h1>
    Edit Article
  </h1>

  <%= render 'form' %>

</div>

app/views/pages/index.html.erb
<div class="tile">
      <h4 align="left">Article 1</h4>
      <h4 align="right">
        <% if !@p1.blank? %>
        <% if !@p1.ranks.blank? %>
        Rank:
        <%= @p1.ranks.average(:rating).round(0) %></h4>
    <% end %>
    <% end %>
      <h1>
        <strong><%= @page1["title"] %></strong>
      </h1>

      <h3><%= @page1["body"][0]["model"]["text"]%></h3>

      <p><%= @page1["body"][1]["model"]["text"]%></p>
      <h1></h1>
      <img src=<%= @page1["body"][2]["model"]["url"] %> alt=<%= @page1["body"][2]["model"]["altText"] %> height="220" width="420">

<% if !@p1.blank? %>
<h1><%= link_to "Read more . . .", page_path(@p1) %></strong></h1>
<% end %>
</div>

app/views/pages/new.html.erb
<div class="tile">

  <h1>
    New Article
  </h1>

  <%= render 'form' %>

</div>

app/views/pages/otherpages.html.erb
<div class="tile">
<h1>Empty Article</h1>

</div>

<br>
<%= render 'show' %>

app/views/pages/page1.html.erb
<div class="tile">
  <h4 align="right">
    <% if !@p1.blank? %>
    <% if !@p1.ranks.blank? %>
    Rank:
    <%= @p1.ranks.average(:rating).round(0) %></h4>
<% end %>
<% end %>
  <h1>
    <strong><%= @page1["title"] %></strong>
  </h1>

  <h3><%= @page1["body"][0]["model"]["text"]%></h3>

  <p><%= @page1["body"][1]["model"]["text"]%></p>
  <h1></h1>
  <img src=<%= @page1["body"][2]["model"]["url"] %> alt=<%= @page1["body"][2]["model"]["altText"] %> height="420" width="640">
  <h1></h1>
  <p><%= @page1["body"][3]["model"]["text"]%></p>
  <p><%= @page1["body"][4]["model"]["text"]%></p>

  <ul style="list-style-type:disc;">
    <li><%= @page1["body"][5]["model"]["items"][0] %></li>
    <li><%= @page1["body"][5]["model"]["items"][1] %></li>
  </ul>

  <br>

<% if !@p2.blank? %>
  <a href=<%= page_path(@p2) %>>
    <img align="right" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Next_Arrow.svg/600px-Next_Arrow.svg.png" width="30" height="30">
  </a>
<% end %>

  <a href=<%= root_path %>>
    <img align="left" src="http://brandmark.io/intro/home.png" width="30" height="30">
  </a>

</div>

<br>
<%= render 'show' %>

app/views/pages/page2.html.erb
<div class="tile">

  <h4 align="right">
    <% if !@p2.blank? %>
    <% if !@p2.ranks.blank? %>
    Rank:
    <%= @p2.ranks.average(:rating).round(0) %></h4>
<% end %>
<% end %>
  <h1>
    <strong><%= @page2["title"] %></strong>
  </h1>

  <h3><%= @page2["body"][0]["model"]["text"]%></h3>
  <h1></h1>
  <img src=<%= @page2["body"][1]["model"]["url"] %> alt=<%= @page2["body"][1]["model"]["altText"] %> height="420" width="640">
  <h1></h1>
  <p><%= @page2["body"][2]["model"]["text"]%></p>
  <p><%= @page2["body"][3]["model"]["text"]%></p>
  <h1></h1>
  <img src=<%= @page2["body"][4]["model"]["url"] %> alt=<%= @page2["body"][4]["model"]["altText"] %> height="420" width="640">
  <h1></h1>
  <p><%= @page2["body"][5]["model"]["text"]%></p>
  <h1></h1>
  <img src=<%= @page2["body"][6]["model"]["url"] %> alt=<%= @page2["body"][6]["model"]["altText"] %> height="420" width="640">
  <h1></h1>
  <p><%= @page2["body"][7]["model"]["text"]%></p>

  <br>

<% if !@p3.blank? %>
  <a href=<%= page_path(@p3) %>>
    <img align="right" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Next_Arrow.svg/600px-Next_Arrow.svg.png" width="30" height="30">
  </a>
<% end %>

<% if !@p1.blank? %>
  <a href=<%= page_path(@p1) %>>
    <img align="left" src="https://image.freepik.com/free-icon/back-navigational-arrow-button-pointing-to-left_318-48409.jpg" width="30" height="30">
  </a>
<% end %>

</div>

<br>
<%= render 'show' %>

app/views/pages/page3.html.erb
<div class="tile">
  <h4 align="right">
    <% if !@p3.blank? %>
    <% if !@p3.ranks.blank? %>
    Rank:
    <%= @p3.ranks.average(:rating).round(0) %></h4>
<% end %>
<% end %>
  <h1>
    <strong><%= @page3["title"] %></strong>
  </h1>

  <h3><%= @page3["body"][0]["model"]["text"]%></h3>

  <p><%= @page3["body"][1]["model"]["text"]%></p>
  <p><%= @page3["body"][2]["model"]["text"]%></p>
  <p><%= @page3["body"][3]["model"]["text"]%></p>
  <p><%= @page3["body"][4]["model"]["text"]%></p>
  <p><%= @page3["body"][5]["model"]["text"]%></p>
  <p><%= @page3["body"][6]["model"]["text"]%></p>
  <p><%= @page3["body"][7]["model"]["text"]%></p>
  <p><%= @page3["body"][8]["model"]["text"]%></p>

  <br>

<% if !@p4.blank? %>
  <a href=<%= page_path(@p4) %>>
    <img align="right" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Next_Arrow.svg/600px-Next_Arrow.svg.png" width="30" height="30">
  </a>
<% end %>

<% if !@p2.blank? %>
  <a href=<%= page_path(@p2) %>>
    <img align="left" src="https://image.freepik.com/free-icon/back-navigational-arrow-button-pointing-to-left_318-48409.jpg" width="30" height="30">
  </a>
<% end %>

</div>

<br>
<%= render 'show' %>

app/views/pages/page4.html.erb
<div class="tile">
  <h4 align="right">
    <% if !@p4.blank? %>
    <% if !@p4.ranks.blank? %>
    Rank:
    <%= @p4.ranks.average(:rating).round(0) %></h4>
    <% end %>
    <% end %>
  <h1>
    <strong><%= @page4["title"] %></strong>
  </h1>

  <h3><%= @page4["body"][0]["model"]["text"]%></h3>
  <p><%= @page4["body"][1]["model"]["text"]%></p>

  <ul style="list-style-type:disc;">
    <li><%= @page4["body"][2]["model"]["items"][0] %></li>
    <li><%= @page4["body"][2]["model"]["items"][1] %></li>
    <li><%= @page4["body"][2]["model"]["items"][2] %></li>
    <li><%= @page4["body"][2]["model"]["items"][3] %></li>
  </ul>

  <p><%= @page4["body"][3]["model"]["text"]%></p>

  <ul style="list-style-type:disc;">
    <li><%= @page4["body"][4]["model"]["items"][0] %></li>
    <li><%= @page4["body"][4]["model"]["items"][1] %></li>
  </ul>

  <p><%= @page4["body"][5]["model"]["text"]%></p>

  <br>

<% if !@p5.blank? %>
  <a href=<%= page_path(@p5) %>>
    <img align="right" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Next_Arrow.svg/600px-Next_Arrow.svg.png" width="30" height="30">
  </a>
<% end %>

<% if !@p3.blank? %>
  <a href=<%= page_path(@p3) %>>
    <img align="left" src="https://image.freepik.com/free-icon/back-navigational-arrow-button-pointing-to-left_318-48409.jpg" width="30" height="30">
  </a>
<% end %>

</div>

<br>
<%= render 'show' %>

app/views/pages/page5.html.erb
<div class="tile">
  <h4 align="right">
    <% if !@p5.blank? %>
    <% if !@p5.ranks.blank? %>
    Rank:
    <%= @p5.ranks.average(:rating).round(0) %></h4>
    <% end %>
    <% end %>
  <h1>
    <strong><%= @page5["title"] %></strong>
  </h1>

  <h3><%= @page5["body"][0]["model"]["text"]%></h3>
  <h1></h1>
  <img src=<%= @page5["body"][1]["model"]["url"] %> alt=<%= @page5["body"][1]["model"]["altText"] %> height="420" width="640">
  <h1></h1>
  <img src=<%= @page5["body"][2]["model"]["url"] %> alt=<%= @page5["body"][2]["model"]["altText"] %> height="420" width="640">
  <h1></h1>
  <p><%= @page5["body"][3]["model"]["text"]%></p>

  <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

  <br>

<% if !@p5.blank? && !@p4.blank? && !@p3.blank? && !@p2.blank? && !@p1.blank? %>
  <a href=<%= rankingpage_path %>>
    <img align="right" src="http://freevector.co/wp-content/uploads/2011/01/70199-work-done.png" width="30" height="30">
  </a>
<% end %>

<% if !@p4.blank? %>
  <a href=<%= page_path(@p4) %>>
    <img align="left" src="https://image.freepik.com/free-icon/back-navigational-arrow-button-pointing-to-left_318-48409.jpg" width="30" height="30">
  </a>
<% end %>

</div>

<br>
<%= render 'show' %>

app/views/pages/rankingpage.html.erb
<div class="tile">
  <h1>
    Ranking Articles
  </h1>
  <br>

  <div class="tile">
    <ul>
        <h4><strong><%= link_to "Rank Article 1", new_page_rank_path(@p1) %></h4></strong>
        <br>
        <h5>Ranks previously given:</h5>
        <% if !@p1.ranks.blank? %>
        <%= render @p1.ranks %>
        <% end %>
        <br>
        <h5>
          <strong>Overall Rank:</strong>
        </h5>
        <% if !@p1.ranks.blank? %>
        <div class="average-rank-rating" data-score=<%= @p1.ranks.average(:rating).round(0) %>></div>
        <% end %>
    </ul>
  </div>

  <br>

  <div class="tile">
    <ul>
        <h4><strong><%= link_to "Rank Article 2", new_page_rank_path(@p2) %></h4></strong>
        <br>
        <h5>Ranks previously given:</h5>
        <% if !@p2.ranks.blank? %>
        <%= render @p2.ranks %>
        <% end %>
        <br>
        <h5>
          <strong>Overall Rank:</strong>
        </h5>
        <% if !@p2.ranks.blank? %>
        <div class="average-rank-rating" data-score=<%= @p2.ranks.average(:rating).round(0) %>></div>
        <% end %>
    </ul>
  </div>

  <br>

  <div class="tile">
    <ul>
        <h4><strong><%= link_to "Rank Article 3", new_page_rank_path(@p3) %></h4></strong>
        <br>
        <h5>Ranks previously given:</h5>
        <% if !@p3.ranks.blank? %>
        <%= render @p3.ranks %>
        <% end %>
        <br>
        <h5>
          <strong>Overall Rank:</strong>
        </h5>
        <% if !@p3.ranks.blank? %>
        <div class="average-rank-rating" data-score=<%= @p3.ranks.average(:rating).round(0) %>></div>
        <% end %>
    </ul>
  </div>

  <br>

  <div class="tile">
    <ul>
        <h4><strong><%= link_to "Rank Article 4", new_page_rank_path(@p4) %></h4></strong>
        <br>
        <h5>Ranks previously given:</h5>
        <% if !@p4.ranks.blank? %>
        <%= render @p4.ranks %>
        <% end %>
        <br>
        <h5>
          <strong>Overall Rank:</strong>
        </h5>
        <% if !@p4.ranks.blank? %>
        <div class="average-rank-rating" data-score=<%= @p4.ranks.average(:rating).round(0) %>></div>
        <% end %>
    </ul>
  </div>

  <br>

  <div class="tile">
    <ul>
        <h4><strong><%= link_to "Rank Article 5", new_page_rank_path(@p5) %></h4></strong>
        <br>
        <h5>Ranks previously given:</h5>
        <% if !@p5.ranks.blank? %>
        <%= render @p5.ranks %>
        <% end %>
        <br>
        <h5>
          <strong>Overall Rank:</strong>
        </h5>
        <% if !@p5.ranks.blank? %>
        <div class="average-rank-rating" data-score=<%= @p5.ranks.average(:rating).round(0) %>></div>
        <% end %>
    </ul>

  </div>

  <br>
  <a href=<%= root_path %>>
    <img align="right" src="http://brandmark.io/intro/home.png" width="30" height="30">
  </a>
</div>

<script>
  $('.rank-rating').raty({
    readOnly: true,
    score: function () {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-rank-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function () {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/pages/show.html.erb
<div class="tile">

<h1><%= @page.title %></h1>
<h2><%= @page.body %></h2>

<ul><li><%= link_to "Read more", controller.show %></li></ul>

<ul><li><%= link_to "Edit", edit_page_path(@page) %></li></ul>
<ul><li><%= link_to "Delete", page_path(@page), method: :delete, data: {confirm: "Are you sure ?" } %></li></ul>
<ul><li><%= link_to "Back", root_path %></li></ul>

</div>