config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'page1', to: 'pages#page1'
  get 'page2', to: 'pages#page2'
  get 'page3', to: 'pages#page3'
  get 'page4', to: 'pages#page4'
  get 'page5', to: 'pages#page5'
  get 'rankingpage', to: 'pages#rankingpage'

  # declares all index, show , new, edit and destroy actions
  resources :pages do
    resources :ranks
  end
  root 'pages#index'
  root to: 'home#index'

  # invalid path redirect
get '*path', to: 'phones#not_found'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<div class="tile">
  <nav class="navbar navbar-default">
    <div class="container">

      <div class="nav navbar-nav navbar-left">

        <a href=<%= root_path %>>
          <img src="http://blog.thepilatessuite.co.uk/wp-content/uploads/2016/08/ls_news.jpg" width="100" height="55">
        </a>
      </div>

      <ul class="nav navbar-nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p></p>
          <a href=<%= new_page_path %>>
            <img src="https://image.flaticon.com/icons/svg/60/60740.svg" width="30" height="30">
          </a>
        <% end %>
      </ul>

    </div>
  </nav>

  <html>
    <head>
      <title>OJNews</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <div class="col-md-10 col-md-offset-9">
      <font color="black"><%= render 'shared/footer' %></font>
    </div>

    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  </div>